# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-28T14:21:54+00:00

from __future__ import annotations

from enum import Enum
from typing import List, Optional

from pydantic import BaseModel, Field


class Energies(BaseModel):
    data: Optional[List[float]] = None
    units: Optional[str] = None


class Flux1(BaseModel):
    data: Optional[List[float]] = None
    units: Optional[str] = None


class Flux(BaseModel):
    energies: Optional[Energies] = Field(
        None,
        description='Particle energies at which omnidirectional flux values are calculated, and their units.\n',
    )
    flux: Optional[Flux1] = Field(
        None,
        description='Corresponding omnidirectional flux values, and their units.\n',
    )


class Flux2(BaseModel):
    units: Optional[str] = None
    value: Optional[float] = None


class FluxAtEnergy(BaseModel):
    flux: Optional[Flux2] = Field(None, description='Particle flux value and units.\n')


class Model(Enum):
    AE9 = 'AE9'
    AP9 = 'AP9'
    SPME = 'SPME'
    SPMH = 'SPMH'
    SPMHE = 'SPMHE'
    SPMO = 'SPMO'


class CoordSys(Enum):
    GDZ = 'GDZ'
    GEO = 'GEO'
    GEI = 'GEI'


class CoordUnits(Enum):
    KM = 'KM'
    RE = 'RE'
